# Auth
ENTER_PIN = "ENTER_PIN"

# Order flow
ORDER_SELECT_CATEGORY = "ORDER_SELECT_CATEGORY"
ORDER_SELECT_PRODUCT = "ORDER_SELECT_PRODUCT"
ORDER_SELECT_QUANTITY = "ORDER_SELECT_QUANTITY"
ORDER_CART_ACTION = "ORDER_CART_ACTION"
ORDER_ENTER_PLAYER_ID = "ORDER_ENTER_PLAYER_ID"
ORDER_CONFIRM = "ORDER_CONFIRM"

# Admin flows
ADMIN_SET_PIN = "ADMIN_SET_PIN"
ADMIN_ADD_CAT = "ADMIN_ADD_CAT"
ADMIN_ADD_NAME = "ADMIN_ADD_NAME"
ADMIN_SET_SUPPLIER = "ADMIN_SET_SUPPLIER"
ADMIN_EDIT_NAME_SELECT = "ADMIN_EDIT_NAME_SELECT"
ADMIN_EDIT_NAME_VALUE = "ADMIN_EDIT_NAME_VALUE"
ADMIN_RENAME_GROUP_SELECT = "ADMIN_RENAME_GROUP_SELECT"
ADMIN_RENAME_GROUP_VALUE = "ADMIN_RENAME_GROUP_VALUE"
ADMIN_CHANGE_STATUS_ID = "ADMIN_CHANGE_STATUS_ID"
ADMIN_CHANGE_STATUS_VALUE = "ADMIN_CHANGE_STATUS_VALUE"
ADMIN_SEARCH_ORDER = "ADMIN_SEARCH_ORDER"
ADMIN_CUSTOMER_DATE_RANGE = "ADMIN_CUSTOMER_DATE_RANGE"
ADMIN_REVOKE_USER = "ADMIN_REVOKE_USER"
ADMIN_RESET_USER = "ADMIN_RESET_USER"

# Access code management
ADMIN_CREATE_CODE_LABEL = "ADMIN_CREATE_CODE_LABEL"
ADMIN_REVOKE_CODE = "ADMIN_REVOKE_CODE"

# API Store management
ADMIN_ADD_STORE_NAME = "ADMIN_ADD_STORE_NAME"
ADMIN_STORE_SET_LIMIT = "ADMIN_STORE_SET_LIMIT"

# User Order Limits
ADMIN_SET_USER_LIMIT_ID = "ADMIN_SET_USER_LIMIT_ID"
ADMIN_SET_USER_LIMIT_VALUE = "ADMIN_SET_USER_LIMIT_VALUE"
